import { Container } from '@chakra-ui/react';
import React, { ReactNode } from 'react';
import Head from 'next/head';
import { Navbar } from './Navbar';

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Hostmate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container maxW='container.xl'>{children}</Container>
    </>
  );
};
