import { Container } from '@chakra-ui/react';
import React, { ReactNode } from 'react';
import Head from 'next/head';
import { Navbar } from './Navbar';
import Script from 'next/script';

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Hostmate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-VV3G6ZNQZY" />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-VV3G6ZNQZY');
        `}
      </Script>
      <Container maxW="container.xl">{children}</Container>
    </>
  );
};
